# Generated by Django 3.0.2 on 2020-01-22 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('status', models.NullBooleanField(default=True, verbose_name='status')),
                ('logo', models.FileField(max_length=500, upload_to='images/teams/', verbose_name='logo')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_created')),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_team', to=settings.AUTH_USER_MODEL, verbose_name='user_updated')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='KindOfTeam',
            fields=[
                ('kindof_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('kindof', models.IntegerField(choices=[(1, 'Futbol 11'), (2, 'Futbol sala'), (3, 'Futbol 8'), (4, 'Futbol 5')], verbose_name='kindof')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generales.Team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'KindOfTeam',
                'verbose_name_plural': 'KindOfTeams',
                'db_table': 'kindof_team',
            },
        ),
        migrations.CreateModel(
            name='categoryTeam',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('category', models.IntegerField(choices=[(0, 'Categoría Unica'), (1, 'Primera categoría Varones'), (2, 'Primera categoría Mujeres'), (3, 'Segunda categoria Varones'), (4, 'Segunda categoria Mujeres'), (5, 'Juvenil Varones'), (6, 'Juvenil Mujeres'), (7, 'Mosco Varones'), (8, 'Mosco Mujeres'), (9, 'Pre-mosco Varones'), (10, 'Pre-mosco Mujeres')], verbose_name='category')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generales.Team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'categoryTeam',
                'verbose_name_plural': 'categoryTeams',
                'db_table': 'category_team',
            },
        ),
    ]
