# Generated by Django 3.0.2 on 2020-01-22 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('challenge_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('status', models.IntegerField(choices=[(1, 'Solicitado'), (2, 'Aceptado'), (3, 'Reprogramado'), (4, 'No Aceptado'), (4, 'Cancelado')], verbose_name='status')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('bond', models.PositiveIntegerField(verbose_name='bond')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generales.Team', verbose_name='local')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_created')),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_challange', to=settings.AUTH_USER_MODEL, verbose_name='user_updated')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_team', to='generales.Team', verbose_name='visitor')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
            },
        ),
        migrations.AlterModelOptions(
            name='categoryteam',
            options={'verbose_name': 'CategoryTeam', 'verbose_name_plural': 'CategoryTeams'},
        ),
        migrations.AddField(
            model_name='categoryteam',
            name='uniform_color',
            field=models.CharField(default='', max_length=50, verbose_name='uniform_color'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('status', models.CharField(max_length=50, verbose_name='status')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generales.Challenge', verbose_name='challenge')),
                ('local_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generales.CategoryTeam', verbose_name='local_category')),
                ('visitor_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_team_category', to='generales.CategoryTeam', verbose_name='visitor_category')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='ChallengeComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('comment', models.CharField(max_length=50, verbose_name='comment')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('deleted', models.NullBooleanField(default=False, verbose_name='deleted')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_created')),
            ],
            options={
                'verbose_name': 'ChallengeComment',
                'verbose_name_plural': 'ChallengeComments',
            },
        ),
        migrations.CreateModel(
            name='UsersTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inserted', models.DateTimeField(auto_now_add=True, verbose_name='date_inserted')),
                ('status', models.NullBooleanField(default=True, verbose_name='status')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generales.Team', verbose_name='team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'UsersTeam',
                'verbose_name_plural': 'UsersTeams',
                'db_table': 'users_team',
                'unique_together': {('user', 'team')},
            },
        ),
    ]
