# Generated by Django 3.0.2 on 2020-01-26 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generales', '0003_auto_20200126_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='local_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generales.CategoryTeam', verbose_name='local_category'),
        ),
        migrations.AlterField(
            model_name='game',
            name='visitor_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_team_category', to='generales.CategoryTeam', verbose_name='visitor_category'),
        ),
        migrations.CreateModel(
            name='Belonging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
