# Generated by Django 3.0.2 on 2020-01-26 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generales', '0004_auto_20200126_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='challengecomment',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user_created',
        ),
        migrations.AddField(
            model_name='categoryteam',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challengecomment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kindofteam',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersteam',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='local_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generales.CategoryTeam', verbose_name='local_category'),
        ),
        migrations.AlterField(
            model_name='game',
            name='visitor_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_team_category', to='generales.CategoryTeam', verbose_name='visitor_category'),
        ),
        migrations.AlterField(
            model_name='usersteam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_staff_player', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.DeleteModel(
            name='Belonging',
        ),
    ]
